//! Build-time code generation for the static data tables.
//!
//! Reads vendored upstream KaTeX JSON snapshots from `vendor/katex-<sha>/`
//! and emits Rust source into `$OUT_DIR`. The hand-written wrappers under
//! `src/` `include!` these generated files and expose typed APIs.
//!
//! Per the project's "no network in build.rs" rule, this script reads only
//! local files. Refreshing the JSON is the job of `cargo xtask
//! vendor-update` (Phase 7); for Phase 2 the snapshots are committed.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let upstream_path = manifest_dir.join("vendor/UPSTREAM");
    let upstream = fs::read_to_string(&upstream_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", upstream_path.display()));
    let version = upstream
        .lines()
        .find_map(|l| l.strip_prefix("version="))
        .expect("vendor/UPSTREAM is missing `version=...`");
    let vendor_dir = manifest_dir.join(format!("vendor/katex-{version}"));

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", upstream_path.display());
    println!("cargo:rerun-if-changed={}", vendor_dir.display());
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_HTML");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    gen_symbols(&vendor_dir, &out_dir);
    gen_macros(&vendor_dir, &out_dir);
    gen_spacing_data(&vendor_dir, &out_dir);
    gen_unicode_accents(&vendor_dir, &out_dir);
    gen_unicode_symbols(&vendor_dir, &out_dir);
    gen_unicode_scripts(&vendor_dir, &out_dir);
    gen_unicode_sup_or_sub(&vendor_dir, &out_dir);
    gen_font_metrics_data(&vendor_dir, &out_dir);
}

fn read_json(path: &Path) -> Value {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_slice(&bytes).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn create_out(out_dir: &Path, name: &str) -> std::io::BufWriter<std::fs::File> {
    let path = out_dir.join(name);
    std::io::BufWriter::new(
        fs::File::create(&path).unwrap_or_else(|e| panic!("create {}: {e}", path.display())),
    )
}

// -- symbols --------------------------------------------------------------

fn gen_symbols(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("symbols.json"));
    let modes = v.as_object().expect("symbols.json: object");

    let mut out = create_out(out, "symbols.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/symbols.json"
    )
    .unwrap();
    writeln!(out, "SymbolTable {{").unwrap();
    for mode in ["math", "text"] {
        let entries: BTreeMap<&String, &Value> = modes[mode]
            .as_object()
            .unwrap_or_else(|| panic!("symbols.{mode}: object"))
            .iter()
            .collect();
        let value_buf: Vec<String> = entries
            .values()
            .map(|info| {
                let info = info.as_object().unwrap();
                let font = match info["font"].as_str().unwrap() {
                    "main" => "Font::Main",
                    "ams" => "Font::Ams",
                    other => panic!("unknown font {other:?}"),
                };
                let group = match info["group"].as_str().unwrap() {
                    "bin" => "Group::Bin",
                    "close" => "Group::Close",
                    "inner" => "Group::Inner",
                    "open" => "Group::Open",
                    "punct" => "Group::Punct",
                    "rel" => "Group::Rel",
                    "accent-token" => "Group::AccentToken",
                    "mathord" => "Group::MathOrd",
                    "op-token" => "Group::OpToken",
                    "spacing" => "Group::Spacing",
                    "textord" => "Group::TextOrd",
                    other => panic!("unknown group {other:?}"),
                };
                let replace = match info.get("replace") {
                    Some(Value::String(s)) => format!("Some({s:?})"),
                    Some(Value::Null) | None => "None".to_string(),
                    other => panic!("unexpected `replace`: {other:?}"),
                };
                format!("SymbolInfo {{ font: {font}, group: {group}, replace: {replace} }}")
            })
            .collect();
        let mut map = phf_codegen::Map::<&str>::new();
        for ((name, _), val) in entries.iter().zip(value_buf.iter()) {
            map.entry(name.as_str(), val);
        }
        writeln!(out, "    {mode}: {},", map.build()).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

// -- macros ---------------------------------------------------------------

fn gen_macros(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("macros.json"));
    let entries: BTreeMap<&String, &Value> = v.as_object().unwrap().iter().collect();

    let mut out = create_out(out, "macros.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/macros.json"
    )
    .unwrap();
    let value_buf: Vec<String> = entries
        .values()
        .map(|body| {
            format!(
                "{:?}",
                body.as_str().expect("macros.json: body must be string")
            )
        })
        .collect();
    let mut map = phf_codegen::Map::<&str>::new();
    for ((name, _), val) in entries.iter().zip(value_buf.iter()) {
        map.entry(name.as_str(), val);
    }
    writeln!(out, "{}", map.build()).unwrap();
}

// -- spacingData ----------------------------------------------------------

// Order MUST match `AtomClass` discriminants in src/types.rs — the
// generated `SpacingTable.rows` is indexed by `class as usize`.
const ATOM_CLASS_KEYS: &[&str] = &[
    "mord", "mop", "mbin", "mrel", "mopen", "mclose", "mpunct", "minner",
];

fn gen_spacing_data(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("spacingData.json"));
    let mut out = create_out(out, "spacing_data.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/spacingData.json"
    )
    .unwrap();
    for (group, name) in [
        ("spacings", "SPACINGS"),
        ("tightSpacings", "TIGHT_SPACINGS"),
    ] {
        let table = v[group].as_object().unwrap();
        writeln!(out, "pub static {name}: SpacingTable = SpacingTable {{").unwrap();
        writeln!(out, "    rows: [").unwrap();
        for left_key in ATOM_CLASS_KEYS {
            writeln!(out, "        [").unwrap();
            let row = table
                .get(*left_key)
                .and_then(|v| v.as_object())
                .cloned()
                .unwrap_or_default();
            for right_key in ATOM_CLASS_KEYS {
                match row.get(*right_key) {
                    Some(m) => {
                        let n = m["number"].as_f64().unwrap();
                        let unit_variant = match m["unit"].as_str().unwrap() {
                            "mu" => "Unit::Mu",
                            "em" => "Unit::Em",
                            "ex" => "Unit::Ex",
                            "pt" => "Unit::Pt",
                            other => panic!("unsupported spacing unit {other:?}"),
                        };
                        writeln!(
                            out,
                            "            Some(Measurement::new({n:?}_f64, {unit_variant})),"
                        )
                        .unwrap();
                    }
                    None => writeln!(out, "            None,").unwrap(),
                }
            }
            writeln!(out, "        ],").unwrap();
        }
        writeln!(out, "    ],").unwrap();
        writeln!(out, "}};").unwrap();
    }
}

// -- unicodeAccents -------------------------------------------------------

fn single_char(s: &str) -> char {
    let mut it = s.chars();
    let c = it.next().unwrap();
    assert!(it.next().is_none(), "expected single-char key, got {s:?}");
    c
}

fn gen_unicode_accents(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("unicodeAccents.json"));
    let entries: BTreeMap<String, &Value> = v
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| (k.clone(), v))
        .collect();

    let mut out = create_out(out, "unicode_accents.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/unicodeAccents.json"
    )
    .unwrap();
    let value_buf: Vec<String> = entries
        .values()
        .map(|info| {
            let info = info.as_object().unwrap();
            let text = format!("{:?}", info["text"].as_str().unwrap());
            let math = match info.get("math") {
                Some(Value::String(s)) => format!("Some({s:?})"),
                None | Some(Value::Null) => "None".to_string(),
                other => panic!("unexpected math: {other:?}"),
            };
            format!("UnicodeAccent {{ text: {text}, math: {math} }}")
        })
        .collect();
    let mut map = phf_codegen::Map::<char>::new();
    let chars: Vec<char> = entries.keys().map(|k| single_char(k)).collect();
    for (c, val) in chars.iter().zip(value_buf.iter()) {
        map.entry(*c, val);
    }
    writeln!(out, "{}", map.build()).unwrap();
}

// -- unicodeSymbols -------------------------------------------------------

fn gen_unicode_symbols(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("unicodeSymbols.json"));
    let entries: BTreeMap<String, &Value> = v
        .as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| (k.clone(), v))
        .collect();

    let mut out = create_out(out, "unicode_symbols.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/unicodeSymbols.json"
    )
    .unwrap();
    let value_buf: Vec<String> = entries
        .values()
        .map(|val| format!("{:?}", val.as_str().unwrap()))
        .collect();
    let mut map = phf_codegen::Map::<char>::new();
    let chars: Vec<char> = entries.keys().map(|k| single_char(k)).collect();
    for (c, val) in chars.iter().zip(value_buf.iter()) {
        map.entry(*c, val);
    }
    writeln!(out, "{}", map.build()).unwrap();
}

// -- unicodeScripts -------------------------------------------------------

fn gen_unicode_scripts(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("unicodeScripts.json"));
    let scripts = v.as_array().unwrap();

    let mut out = create_out(out, "unicode_scripts.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/unicodeScripts.json"
    )
    .unwrap();
    writeln!(out, "&[").unwrap();
    for s in scripts {
        let name = s["name"].as_str().unwrap();
        writeln!(out, "    Script {{ name: {name:?}, blocks: &[").unwrap();
        for block in s["blocks"].as_array().unwrap() {
            let arr = block.as_array().unwrap();
            let lo = arr[0].as_u64().unwrap() as u32;
            let hi = arr[1].as_u64().unwrap() as u32;
            writeln!(out, "        ({lo}, {hi}),").unwrap();
        }
        writeln!(out, "    ] }},").unwrap();
    }
    writeln!(out, "]").unwrap();
}

// -- unicodeSupOrSub ------------------------------------------------------

fn gen_unicode_sup_or_sub(vendor: &Path, out: &Path) {
    let v = read_json(&vendor.join("unicodeSupOrSub.json"));
    let map_obj = v["uSubsAndSups"].as_object().unwrap();
    let regex = v["unicodeSubRegEx"].as_str().unwrap();
    let entries: BTreeMap<String, &Value> = map_obj.iter().map(|(k, v)| (k.clone(), v)).collect();

    let mut out = create_out(out, "unicode_sup_or_sub.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/unicodeSupOrSub.json"
    )
    .unwrap();
    writeln!(out, "pub static UNICODE_SUB_REGEX: &str = {regex:?};").unwrap();
    let value_buf: Vec<String> = entries
        .values()
        .map(|val| format!("{:?}", val.as_str().unwrap()))
        .collect();
    let mut map = phf_codegen::Map::<char>::new();
    let chars: Vec<char> = entries.keys().map(|k| single_char(k)).collect();
    for (c, val) in chars.iter().zip(value_buf.iter()) {
        map.entry(*c, val);
    }
    writeln!(
        out,
        "pub static U_SUBS_AND_SUPS: ::phf::Map<char, &'static str> = {};",
        map.build()
    )
    .unwrap();
}

// -- fontMetricsData ------------------------------------------------------

fn gen_font_metrics_data(vendor: &Path, out: &Path) {
    let mut out = create_out(out, "font_metrics_data.rs");
    writeln!(
        out,
        "// @generated by build.rs from vendor/katex-*/fontMetricsData.json"
    )
    .unwrap();
    // Skip phf-codegen for the ~155k-entry full table when the `html`
    // feature isn't on — saves the dominant build.rs cost on default
    // (MathML-only) builds. Phase 6 may surface a small subset for
    // MathML; the empty map is the placeholder until then.
    // Vendored metrics include numeric values that clippy flags as
    // approximations of math constants (e.g. 0.78539 ≈ π/4). The data
    // is copied verbatim from upstream KaTeX's font tables, so silence
    // the lint on the static itself.
    writeln!(out, "#[allow(clippy::approx_constant)]").unwrap();
    if env::var_os("CARGO_FEATURE_HTML").is_none() {
        let empty = phf_codegen::Map::<&str>::new().build().to_string();
        writeln!(
            out,
            "pub static FONT_METRICS_DATA: ::phf::Map<&'static str, ::phf::Map<u32, CharacterMetrics>> = {empty};"
        )
        .unwrap();
        return;
    }

    let v = read_json(&vendor.join("fontMetricsData.json"));
    let entries: BTreeMap<&String, &Value> = v.as_object().unwrap().iter().collect();
    let inner_exprs: Vec<String> = entries
        .values()
        .map(|glyph_map| {
            let glyphs = glyph_map.as_object().unwrap();
            let mut pairs: Vec<(u32, &Value)> = glyphs
                .iter()
                .map(|(k, v)| (k.parse::<u32>().unwrap(), v))
                .collect();
            pairs.sort_unstable_by_key(|(cp, _)| *cp);
            let metrics_exprs: Vec<String> = pairs
                .iter()
                .map(|(_, arr)| {
                    let nums: Vec<String> = arr
                        .as_array()
                        .unwrap()
                        .iter()
                        .map(|n| format!("{:?}_f64", n.as_f64().unwrap()))
                        .collect();
                    format!("[{}]", nums.join(", "))
                })
                .collect();
            let mut inner = phf_codegen::Map::<u32>::new();
            for ((cp, _), val) in pairs.iter().zip(metrics_exprs.iter()) {
                inner.entry(*cp, val);
            }
            inner.build().to_string()
        })
        .collect();
    let mut outer = phf_codegen::Map::<&str>::new();
    for ((name, _), val) in entries.iter().zip(inner_exprs.iter()) {
        outer.entry(name.as_str(), val);
    }
    writeln!(
        out,
        "pub static FONT_METRICS_DATA: ::phf::Map<&'static str, ::phf::Map<u32, CharacterMetrics>> = {};",
        outer.build()
    )
    .unwrap();
}
